[package]
name = "tonytools-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bimap = "0.6.3"
crc32fast = "1.4.0"
once_cell = "1.19.0"
num = "0.4.1"
